### ISSUE TITLE
Test script error

### ISSUE THREAD

**Issue by riddhimandhar** [BIMIB-DISCo/scFBA#3]
Hello, 
When we run the scFBA_test using cobra toolbox v2.0, we get the following error - 

Unrecognized function or variable 'buildRxnGeneMat'.

Error in ScFBAExpSetting (line 122)
model = buildRxnGeneMat(model); %generate rxnGeneMat field

Error in scFBA_test (line 47)
HMRcore = ScFBAExpSetting(HMRcore, length(BC04.CellType));

I am using the cobra toolbox from here and it seems that the buildRxnGeneMat function is not there in this version https://github.com/opencobra/cobratoolbox/releases/tag/v2.0.0. 

I could find this function in cobra toolbox v3.0. 

Is there a specific version of cobra toolbox that we should use? 

Thanks a lot.

**Comment by DavideMaspero** [comment]
Hi,
I just run scFBA_test with cobra toolbox 2021 updated, without any problems.
I think you may try to use it or add the 'buildRxnGeneMat' function into your matlab path.

Hope these suggestments will fix your issue.

Best,
Davide

**Comment by riddhimandhar** [comment]
Hi,
Thank you for your reply. 
I tried with the latest cobra toolbox and I see the following errors - 

Delete gene(s) in population model
Compute RAS
Starting parallel pool (parpool) using the 'local' profile ...
Connected to the parallel pool (number of workers: 12).
Integrate RAS in model
Error using parseCobraVarargin (line 129)
The value of 'osenseStr' is invalid. It must satisfy the function: @(x)strcmp(x,'max')|strcmp(x,'min').

Error in fluxVariability (line 115)
[funParams, cobraParams, solverVarargin] = parseCobraVarargin(varargin, optArgin, defaultValues, validator, problemTypes, 'solverParams', true);

Error in integrateRAS (line 32)
[Fmin,FMax] = fluxVariability(modelPop, 100, '', RxnList); %controllare che 100 vada bene

Error in single2IntPopModel (line 87)
    scStruct = integrateRAS(scStruct, 'modelDel');

Error in scFBA_test (line 53)
BC04 = single2IntPopModel(BC04, HMRcore, IdxExRxns, IdxCoopRxn, 's');


These errors do not appear with cobratoolbox v2 but the buildRxnGeneMat function does not seem to be included there. 

I am running Matlab 2019b and gurobi 9.1.1.

**Comment by DavideMaspero** [comment]
Hi,

You can try to use cobra v2.0, then add  into your matlab path only the 'buildRxnGeneMat.m' function from the cobra v3.0 toolbox.

Best,
Davide

**Comment by riddhimandhar** [comment]
Thanks, it works now!
